version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
#      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db_bank_app
      MYSQL_USER: root
      MYSQL_PASSWORD: 1403
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8081:8081"
      - "1025:1025"
      - "1080:1080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/my_db_bank_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1403