spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/my_db_bank_app
    username: developer
    password: password

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
app:
  description: Dev version
  version: 0.0.1-SNAPSHOT
  server:
    stage: dev